### ISSUE TITLE
[FEAT] Remove ai from Google results

### ISSUE THREAD

**Issue by k4lizen** [hearchco/agent#309]
Google supposedly returns AI results by default, and supposedly the `&udm=14` parameter disables it.

**Comment by aleksasiriski** [comment]
From my limited testing, this just sets the category to "web" which means that only the results we scrape are rendered in the HTML (w/o any images or other panels that are usually available on the default (called "all") category).

Since I don't think this would make scraping any faster and it doesn't change the results we get, it would only make it look less than a normal user, so it's IMO best not to use this param.

If I'm mistaken about the results, please correct me.
